### ISSUE TITLE
ORM 환경설정 .env에서 ormconfig.ts로 이사가는게 어떨까요?

### ISSUE THREAD

**Issue by moaikang** [boostcamp-2020/IssueTracker-15#121]
### 의논거리 🤔 
- 기존에 데이터베이스 config를 위해 `.env`를 사용했습니다.
- 이를 `ormconfig.ts` 으로 바꾸는게 어떨까 의논하고 싶습니다.

 > 테스팅을 하기 위해서 데이터베이스 두 개를 사용할까 합니다. 
 > 데이터베이스 하나는 실제 서비스 DB이고, 하나는 테스팅용 DB(로컬 DB)로 하고 싶습니다. 
 > 이 때, 테스트용 DB는 테스트가 끝나고 난 뒤 데이터가 사라져야 합니다.
> 이를 `.env` 하나로 처리하기엔 너무 복잡하고, `ormconfig.ts`로 처리하면 좋을거 같습니다.

**예시**
```typescript
import { ConnectionOptions } from "typeorm";

const connectionOptions: ConnectionOptions[] = [
  {
    name: "default",
    type: "mysql",
    database: 'db',
    synchronize: false,
    logging: true,
    entities: [__dirname + "/src/entities/**/*.ts"],
    subscribers: [__dirname + "/src/subscribers/**/*.ts"],
    migrations: [__dirname + "/databases/migrations/**/*.ts"],
    migrationsTableName: "migrations",
    cli: {
      entitiesDir: "src/entities",
      subscribersDir: "src/subscribers",
      migrationsDir: "databases/migrations"
    },
    host: 'host',
    port: 'port',
    username: 'user',
    password: 'password'
  },
  {
    name: "test",
    type: "mysql",
    database: 'db_test',
    synchronize: true,
    dropSchema: true, // 이게 DB 커넥션 끊길 때, 데이터 전부 다 지우는 옵션.
    logging: false,
    entities: [__dirname + "/src/entities/**/*.ts"],
    subscribers: [__dirname + "/src/subscribers/**/*.ts"],
    migrations: [__dirname + "/databases/migrations/**/*.ts"],
    host: 'host',
    port: 'port',
    username: 'user',
    password: 'password'
  }
];

export = connectionOptions;
```

**Comment by namda-on** [comment]
.env 로도 development option을 줄 수 있을 것 같아요 
package.json 에서
```
    "start": "nest start",
    "test" : "mode = development jest ~~~"
    "start:dev": "nest start --watch",
```
이런 식으로 mode=development라는 환경변수를 주어서 dotenv.config() 를 하기전에 if문으로 config를 할 .env를 골라서 설정해줄 수 있을것같긴해요! 

편한 방식을 채택하면 될것같습니다!

**Comment by maong0927** [comment]
저는 ormconfig 파일을 따로 쓰는 거에 긍정적인 의견입니당 
근우님이 말씀하신 이유 이외에도 다른 모든 설정들을 각각의 파일에서 하고 있어서 
env 에 넣어두는 거 보다 따로 파일을 만드는 것이 나을 거 같아용  ( 가독성 측면에서 ) 
단지 다른 설정들이 모두 json 형식으로 되어있어서 ormconfig 파일도 json 방식으로 하는 게 좋을거 같아요

**Comment by moaikang** [comment]
> 저는 ormconfig 파일을 따로 쓰는 거에 긍정적인 의견입니당
> 근우님이 말씀하신 이유 이외에도 다른 모든 설정들을 각각의 파일에서 하고 있어서
> env 에 넣어두는 거 보다 따로 파일을 만드는 것이 나을 거 같아용 ( 가독성 측면에서 )
> 단지 다른 설정들이 모두 json 형식으로 되어있어서 ormconfig 파일도 json 방식으로 하는 게 좋을거 같아요

@maong0927 

저도 `.json` 을 쓰는게 더 네이밍의 일관성이 좋을거 같아요.
다만, 옵션이 2개 이상이기 때문에 배열이 들어가야 해서(위의 코드의 경우 `ConnectionOptions`) `.json`을 사용하기 힘들 수도  있을거 같다는 생각이 들어요 ㅠㅠ
