### ISSUE TITLE
서버에서 가져올 Milestone 정보에 대한 논의

### ISSUE THREAD

**Issue by SHIVVVPP** [boostcamp-2020/IssueTracker-15#95]
### 의논거리 🤔 
MilestoneList 화면에서 Open Issue의 수, Close Issue의 수, 진행 정도 (Open * 100 /(Open+Closed))% 가 표시 되어야 해서
MilestoneList 요청시 위 정보들도 같이 받아야 할 것 같습니다!

### 관련 PR or Issue Number

- PR :  X
- Issue : X

### 이미지
![image](https://user-images.githubusercontent.com/34773827/97524758-c3062900-19e8-11eb-8a9f-6c51ca319ef9.png)

**Comment by maong0927** [comment]
네 알겠습니다~ 서버에서 보내도록 하겠습니다!

**Comment by SHIVVVPP** [comment]
🙇 감사합니다 ~
